import { existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

const blogDir = resolve(import.meta.dirname, 'blog')

// The blog is a set of extra HTML entry points generated by scripts/build-blog.mjs.
// Vite reads this when it loads the config, so the folder has to exist first —
// that is what the npm `prebuild`/`predev` hooks are for.
function blogEntries() {
  if (!existsSync(blogDir)) return {}
  const entries = { blog: resolve(blogDir, 'index.html') }
  for (const name of readdirSync(blogDir, { withFileTypes: true })) {
    if (name.isDirectory()) {
      entries[`blog-${name.name}`] = resolve(blogDir, name.name, 'index.html')
    }
  }
  return entries
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  build: {
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, 'index.html'),
        ...blogEntries(),
      },
    },
  },
})
