import { existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

const blogDir = resolve(import.meta.dirname, 'blog')

// The blog is a set of extra HTML entry points generated by scripts/build-blog.mjs.
// Vite reads this when it loads the config, so the folder has to exist first —
// that is what the npm `prebuild`/`predev` hooks are for.
function blogEntries() {
  if (!existsSync(blogDir)) return {}
  const entries = { blog: resolve(blogDir, 'index.html') }
  for (const name of readdirSync(blogDir, { withFileTypes: true })) {
    if (name.isDirectory()) {
      entries[`blog-${name.name}`] = resolve(blogDir, name.name, 'index.html')
    }
  }
  return entries
}

// The contact form POSTs to `/api/contact`, which in production is a
// CloudFront behaviour in front of the contact Lambda. In dev there is no
// CloudFront, so proxy the same path straight at the Function URL — same
// fetch, same origin, no CORS. Put the stack's `ContactFunctionUrl` output in
// `.env` as CONTACT_FN_URL; without it the form fails in dev only.
function contactProxy(mode) {
  const { CONTACT_FN_URL } = loadEnv(mode, import.meta.dirname, '')
  if (!CONTACT_FN_URL) return {}
  return {
    // The Function URL serves the handler at its root, so the path is
    // rewritten away rather than forwarded.
    '/api/contact': {
      target: CONTACT_FN_URL,
      changeOrigin: true,
      rewrite: () => '/',
    },
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => ({
  plugins: [react()],
  server: {
    proxy: contactProxy(mode),
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(import.meta.dirname, 'index.html'),
        ...blogEntries(),
      },
    },
  },
}))
