import React from "react";
import recentPosts from "../data/recent-posts.json";

// recent-posts.json is generated by scripts/build-blog.mjs from the same
// Markdown the blog pages are built from, so these titles cannot go stale.

const Medium = () => {
  return (
    <div className="portfolio-portfolioItem portfolio-portfolioItem--imageRight">
      <div className="portfolio-portfolioItemText">
        <h2 className="portfolio-portfolioItemTitle">Blog</h2>
        <p>
          I write about all things software development: architecture,
          scalability, AI, and real-world lessons from building production
          systems.
        </p>

        {recentPosts.length > 0 && (
          <ul className="writing-recentPosts">
            {recentPosts.map((post) => (
              <li key={post.path}>
                <a className="writing-appLink" href={post.path}>
                  {post.title}
                </a>
              </li>
            ))}
          </ul>
        )}

        <div className="portfolio-portfolioButtonContainer">
          <div className="portfolio-portfolioButton">
            <a href="/blog/" className="button">
              Read My Articles
            </a>
          </div>
          <p className="writing-syndication">
            Also published on{" "}
            <a
              className="writing-appLink"
              href="https://medium.com/@shanehobson1"
              target="_blank"
              rel="noopener noreferrer"
            >
              Medium
            </a>
            .
          </p>
        </div>
      </div>
      <div
        className="portfolio-portfolioItemImage"
        id="portfolio-bookImage"
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          cursor: "pointer",
        }}
      >
        <a href="/blog/">
          <img
            src="/images/medium.webp"
            width="560"
            height="280"
            loading="lazy"
            decoding="async"
            alt="Articles by Shane Hobson"
          ></img>
        </a>
      </div>
    </div>
  );
};

export default Medium;
