import recentPosts from "../data/recent-posts.json";

// recent-posts.json is generated by scripts/build-blog.mjs from the same
// Markdown the blog pages are built from, so these titles cannot go stale.
const Writing = () => (
  <section className="section writing" id="writing">
    <div className="shell">
      <header className="writing-head">
        <p className="eyebrow">02 / Writing</p>
        <h2 className="section-title">Writing</h2>
      </header>

      <div className="writing-grid">
        <article className="writing-card">
          <a
            className="writing-card-media writing-card-media--blog"
            href="/blog/"
          >
            <img
              src="/images/blog.webp"
              width="1050"
              height="787"
              loading="lazy"
              decoding="async"
              alt="Articles by Shane Hobson"
            />
          </a>
          <div className="writing-card-body">
            <h3 className="writing-card-title">Blog</h3>
            <p>
              I write about all things software development: architecture,
              scalability, AI, and real-world lessons from building production
              systems.
            </p>

            {recentPosts.length > 0 && (
              <ul className="writing-posts">
                {recentPosts.map((post) => (
                  <li key={post.path}>
                    <a href={post.path}>
                      <span className="writing-posts-arrow" aria-hidden="true">
                        →
                      </span>
                      {post.title}
                    </a>
                  </li>
                ))}
              </ul>
            )}

            <div className="writing-card-actions">
              <a className="button" href="/blog/">
                Read my articles
              </a>
              <p className="writing-syndication">
                Also published on{" "}
                <a
                  className="link"
                  href="https://medium.com/@shanehobson1"
                  target="_blank"
                  rel="noreferrer"
                >
                  Medium
                </a>
                .
              </p>
            </div>
          </div>
        </article>

        <article className="writing-card">
          <a
            className="writing-card-media writing-card-media--book"
            href="https://www.amazon.com/How-Become-Self-Taught-Software-Developer/dp/B0CCCHSC82"
            target="_blank"
            rel="noreferrer"
          >
            <img
              src="/images/Book.webp"
              width="509"
              height="346"
              loading="lazy"
              decoding="async"
              alt="How To Become a Self-Taught Software Developer"
            />
          </a>
          <div className="writing-card-body">
            <h3 className="writing-card-title">
              How To Become a Self-Taught Software Developer
            </h3>
            <p>
              I taught myself how to code while working as an attorney in 2016.
              After successfully landing a job in software development, I began
              helping others pursue the goal of becoming a software developer
              without a traditional computer science education. Eventually, I
              decided to formally document the step-by-step process of becoming
              a self-taught software developer, and the result was this book.
              Since its publication, the book has helped hundreds of others
              pursue their dream of breaking into the software industry.
            </p>
            <div className="writing-card-actions">
              <a
                className="button"
                href="https://www.amazon.com/How-Become-Self-Taught-Software-Developer/dp/B0CCCHSC82"
                target="_blank"
                rel="noreferrer"
              >
                Buy the book
              </a>
            </div>
          </div>
        </article>
      </div>
    </div>
  </section>
);

export default Writing;
